[build]
  # Esta es la carpeta que Netlify publicará.
  publish = "public"

[[redirects]]
  # "from" es la página que pide el usuario (la raíz).
  from = "/"
  # "to" es el archivo que Netlify debe mostrar.
  to = "/views/index.html"
  # "status 200" significa que es una reescritura (no una redirección).
  status = 200